# Generated by Django 3.2.6 on 2021-08-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRimgtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('total_cases', models.IntegerField(null=True)),
                ('total_deaths', models.IntegerField(null=True)),
                ('new_deaths', models.IntegerField(null=True)),
                ('total_vaccinations', models.IntegerField(null=True)),
                ('people_vaccinated', models.IntegerField(null=True)),
                ('people_fully_vaccinated', models.IntegerField(null=True)),
                ('total_vaccinations_per_hundred', models.IntegerField(null=True)),
                ('people_vaccinated_per_hundred', models.IntegerField(null=True)),
                ('new_vaccinations', models.IntegerField(null=True)),
            ],
        ),
    ]
