# Generated by Django 3.2.6 on 2021-08-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19BotApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DRimgtable',
            new_name='covid7dayInfo',
        ),
    ]
