# Generated by Django 3.2.6 on 2021-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19BotApp', '0002_rename_drimgtable_covid7dayinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid7dayinfo',
            name='new_cases',
            field=models.IntegerField(null=True),
        ),
    ]
