# Generated by Django 3.2.6 on 2021-08-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19BotApp', '0004_auto_20210824_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid7dayinfo',
            name='Chinese_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='covid7dayinfo',
            name='date_str',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
