# Generated by Django 3.2.6 on 2021-09-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('assets_debt', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('TWD_exchange', models.FloatField(blank=True, null=True)),
                ('assets_QTY', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bigexpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('bigexpend_type', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('bigexpend_QTY', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='endMeets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('Y', models.IntegerField(null=True)),
                ('M', models.IntegerField(null=True)),
                ('year_month', models.DateField()),
                ('assets_TWD', models.FloatField(blank=True, null=True)),
                ('income_TWD', models.FloatField(blank=True, null=True)),
                ('expend_TWD', models.FloatField(blank=True, null=True)),
                ('end_meets', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='expend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('expend_type', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('expend_QTY', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('income_type', models.CharField(max_length=100)),
                ('TWD_exchange', models.FloatField(blank=True, null=True)),
                ('income_QTY', models.IntegerField(null=True)),
            ],
        ),
    ]
