# Generated by Django 3.2.6 on 2021-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('assets_debt', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('TWD_exchange', models.FloatField(blank=True, null=True)),
                ('assets_QTY', models.IntegerField(null=True)),
            ],
        ),
    ]
