# Generated by Django 3.2.6 on 2021-09-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='assets_QTY',
            new_name='debt_QTY',
        ),
    ]
