# Generated by Django 3.2.6 on 2021-09-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_assets_qty_debt_debt_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='endmeets',
            name='debt_TWD',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
